### ISSUE TITLE
OMG Sindre!

### ISSUE THREAD

**Issue by nzmedet** [sindresorhus/year-days#2]
Why you keep creating so much packages hmm?
Don't get me wrong, i just wonder how you get the idea of making packages

**Comment by sindresorhus** [comment]
I create most packages out of need. I make larger packages that I either extract functionality out of or make packages I need to solve problems in my bigger projects.

**Comment by sholladay** [comment]
@vko-online see https://github.com/sindresorhus/ama/issues/13 and https://github.com/sindresorhus/ama/issues/1 (not answered yet, but hopefully soon)
